#   gem install pg
#
#   Ensure the postgreSQL gem is defined in your Gemfile
#   gem 'pg'
#

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres      # Default PostgreSQL username
  password: Doofenshmirtz64$

development:
  <<: *default
  database: interviewProject

test:
  <<: *default
  database: interviewProject_test

production:
  <<: *default
  database: interviewProject_production
